// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const UserSecretsLoginCredentialsSchema = z.object({
  id: z.string().uuid(),
  name: z.string().nullable().optional(),
  username: zodBuffer,
  password: zodBuffer,
  userId: z.string().uuid(),
  orgId: z.string().uuid()
});

export type TUserSecretsLoginCredentials = z.infer<typeof UserSecretsLoginCredentialsSchema>;
export type TUserSecretsLoginCredentialsInsert = Omit<
  z.input<typeof UserSecretsLoginCredentialsSchema>,
  TImmutableDBKeys
>;
export type TUserSecretsLoginCredentialsUpdate = Partial<
  Omit<z.input<typeof UserSecretsLoginCredentialsSchema>, TImmutableDBKeys>
>;
